name: Docker Image
on:
  push:
    branches:
      - "main"
      - "ci"

env:
  REGISTRY: 295114534192.dkr.ecr.us-west-2.amazonaws.com
  IMAGE_NAME: website
  AWS_REGION: us-west-2
  CLUSTER: m1-prod-6x3kk4

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2.3.3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/txpipe/rfcs,ghcr.io/txpipe/rfcs:${{ github.sha }}
